// src/components/BasicApiTest.tsx

import React from 'react';
import { sites, events } from '@/api/apiClient'


const userId = '9446217e-49e8-49f9-84dc-822ed8df969b'

const example_site = {
  title: 'Test Site',
  url: 'https://my_example.com',
  description: 'Test site created via API',
  user_id: '9446217e-49e8-49f9-84dc-822ed8df969b',
  accessible: true,
  domain_exists: true,
  html_content_exists: false,
  is_public: true,
  secure: true,
  status_code: 200,
  type: 'example_type',
  valid_url: true,
  AI: false,
  id_area: 1,
  id_cat: 1,
  tag_3: 3,
  tag_4: 4,
  tag_5: 5,
  id_provider: 1,
  ratings: 4,
  AI_think: 'AI analysis',
  AI_summary: 'Summary generated by AI',
  context_id: '1',      // Changed to string
  resource_id: '1',     // Changed to string
  function_id: '1'      // Changed to string
}

const example_new_event = {
  id_event_type: 3,
  id_event_family: 2,
  user_id: '9446217e-49e8-49f9-84dc-822ed8df969b'
}

const example_update_event = {
  id: 5,
  id_event_type: 8,
  id_event_family: 2
}

const BasicApiTest = () => {
  const handleTestClick = async () => {
    console.log('🔄 Avvio chiamate api...')

    try {

      const _sites = await sites.getAll(); // Chiama la funzione definita in apiClient
      console.log('✅ Risultato della chiamata:', _sites)
      const _sites_by_id = await sites.getOne(156); // Chiama la funzione definita in apiClient
      console.log('✅ Risultato della chiamata:', _sites_by_id)
      const _sites_by_user = await sites.getByUserId(userId); // Chiama la funzione definita in apiClient
      console.log('✅ Risultato della chiamata:', _sites_by_user)
      const _sites_post = await sites.create(example_site); // Chiama la funzione definita in apiClient
      const _events_logs = await events.getAll(); // Chiama la funzione definita in apiClient
      console.log('✅ Risultato della chiamata:', _events_logs)
      const _post_event = await events.create(example_new_event); // Chiama la funzione definita in apiClient
      console.log('✅ Risultato della chiamata:', _events_logs)
    } catch (error) {
      console.error('❌ Errore durante la chiamata:', error)
    }
  }


  return (
    <div>
      <button
        onClick={handleTestClick}
        style={{
          padding: '10px 20px',
          backgroundColor: '#3b82f6',
          color: 'white',
          border: 'none',
          borderRadius: '4px',
          cursor: 'pointer'
        }}
      >
        Test getSites
      </button>
    </div>
  );
};

export default BasicApiTest;